name: Build and Deploy React App to S3 and Elastic Beanstalk

on:
  push:
    branches: [monolith]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Define environment variables
    env:
      APP_NAME: "qr-react-app"        # Elastic Beanstalk application name
      ENV_NAME: "Qr-react-app-env"          # Elastic Beanstalk environment name
      S3_BUCKET: "qr-react-app-bk"  # S3 bucket name
      AWS_REGION: "us-west-1"  # AWS region

    # Set the default working directory for all steps to frontend
    defaults:
      run:
        working-directory: frontend   

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.11.0'

    # Step 3: Install dependencies and build the React app
    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    # Step 4: Zip the application
    - name: Zip the application
      run: |
        mkdir -p deployment
        cp -r server/* deployment/  # Copy the built React app
        cd deployment
        zip -r ../${{ env.APP_NAME }}.zip .

    # Step 5: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Step 6: Upload the zip file to S3
    - name: Upload to S3
      run: |
        aws s3 cp ${{ env.APP_NAME }}.zip s3://${{ env.S3_BUCKET }}/app-${{ github.sha }}.zip
        echo "S3 URL: s3://${{ env.S3_BUCKET }}/app-${{ github.sha }}.zip"

    # Step 7: Update Elastic Beanstalk environment
    - name: Update Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name "${{ env.APP_NAME }}" \
          --version-label "v${{ github.sha }}" \
          --source-bundle S3Bucket="${{ env.S3_BUCKET }}",S3Key="app-${{ github.sha }}.zip"
        
        aws elasticbeanstalk update-environment \
          --environment-name "${{ env.ENV_NAME }}" \
          --version-label "v${{ github.sha }}"
